## Tasca S3 T01

In [1]:
import numpy as np

### Exercici 1

*Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.*

In [2]:
def stat_basic(arr):
    if arr.ndim <= 1:
        print(f'media aritmetica: {np.mean(arr)}')
        print(f'mediana: {np.median(arr)}')
        print(f'desviación tipica: {np.std(arr)}')
        print(f'varianza: {np.var(arr)}')
    else:
        print('ERROR')

In [3]:
arr1 = np.array([3,5,7])

stat_basic(arr1)

media aritmetica: 5.0
mediana: 5.0
desviación tipica: 1.632993161855452
varianza: 2.6666666666666665


### Exercici 2

Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.

In [4]:
def matriu_quadrat():
    N = int(input("Enter N: "))
    
    #valors aleatoris entre el 0 i el 100.
    return np.random.randint(101, size=(N,N)) 

In [5]:
matriu_quadrat()

Enter N: 3


array([[55, 15, 49],
       [ 4, 93, 80],
       [68, 84, 38]])

### Exercici 3

Crea una funció que donada una taula de dues dimensions (NxM), et calculi els totals per fila i els totals per columna.

In [6]:
def matriu_totals():
    N = int(input("Enter número files: "))
    M = int(input("Enter número columnes: "))
    
    array = np.random.randint(10, size=(N,M)) #valors aleatoris entre el 0 i el 10.
    
    print(array)
    
    return np.sum(array, axis=1), np.sum(array, axis=0) #calcul totals fila i columna

In [7]:
matriu_totals()

Enter número files: 5
Enter número columnes: 7
[[5 9 9 8 4 0 5]
 [5 7 9 1 2 0 0]
 [1 1 7 1 6 4 0]
 [4 6 2 6 6 6 2]
 [8 6 9 2 3 1 3]]


(array([40, 24, 20, 32, 32]), array([23, 29, 36, 18, 21, 11, 10]))

### Exercici 4

Implementa manualment una funció que calculi el coeficient de correlació. Informa-te'n sobre els seus usos i interpretació.

In [8]:
#Prueba de coeficiente de correlación entre dos variables (altura y peso)
altura = np.array([1.75, 1.59, 1.66, 1.66, 1.68])
peso = np.array([82, 68, 70, 61, 70])

In [9]:
#Número total de elementos
n = len(altura)
print(n)

5


In [10]:
#Calcular la media de X
x_mean = np.mean(altura)
print(x_mean)

1.668


In [11]:
#Calcular la media de Y
y_mean = np.mean(peso)
print(y_mean)

70.2


In [12]:
#calcular la desviación estandard de X
st_dev_x = np.std(altura)
print(st_dev_x)

0.051146847410177665


In [13]:
#Calcular la desviación estandard de Y
st_dev_y = np.std(peso)
print(st_dev_y)

6.764613810115105


In [14]:
def num1(altura):
    list = []

    for n in altura:
        var1 = n - x_mean
        list.append(var1)
    
    return list

In [15]:
def num2(peso):
    list1 = []
    
    for p in peso:
        var2 = p - y_mean
        list1.append(var2)
    
    return list1

In [16]:
#Calcular desviación de cada punto "X" respecto a la media 
num1(altura)

[0.08200000000000007,
 -0.07799999999999985,
 -0.008000000000000007,
 -0.008000000000000007,
 0.01200000000000001]

In [17]:
#Calcular desviación de cada punto "Y" respecto a la media 
num2(peso)

[11.799999999999997,
 -2.200000000000003,
 -0.20000000000000284,
 -9.200000000000003,
 -0.20000000000000284]

In [18]:
#Completamos el numerador de la ecuación
var3 = sum(np.multiply(num1(altura),num2(peso)))
print(var3)

1.2120000000000009


In [19]:
#Hallamos el coeficiente de correlación
r = (1/n)*(var3)/(st_dev_x*st_dev_y)
print(round(r, 8))

0.70060098


In [20]:
#Comparamos el resultado obtenido con el de la formula
np.corrcoef(altura, peso)

array([[1.        , 0.70060098],
       [0.70060098, 1.        ]])

Existeix una correlació positiva, on alçada i pes estan fortament relacionats